[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "brave-context-downloader"
version = "0.0.2"
readme = "README.md"
description = "A downloader for brave context"

dependencies = [
    "requests",
    "selenium",
    "PyCryptodome",
]
